### ISSUE TITLE
Nightly dependency

### ISSUE THREAD

**Issue by Phaiax** [mattico/elasticlunr-rs#1]
Hey @mattico, I'll just write here :)

Do you know that the current elasticlunr depends on nightly? (from phf)

-- Daniel

**Comment by mattico** [comment]
Yep, I'll have to do a bit of work to get it to use code generation. Just realized I won't have to do that for serde since custom derive is stable 🎉. I'll focus on that once I get this to output working indexes.

**Comment by mattico** [comment]
Fixed in b110edc6d478b84cebcd8df6cf0a461302db22bb
