### ISSUE TITLE
Multi-byte characters cause a panic.

### ISSUE THREAD

**Issue by bwinton** [mattico/elasticlunr-rs#22]
As reported in https://github.com/rust-lang-nursery/mdBook/issues/971

Pull request incoming…

**Comment by EUSKR** [comment]
@mattico looks like this issue has returned, I was able to reproduce a similar behavior when running mdBook installed via cargo install (which uses elasticlunr-rs v3.0.3). The issue does not reproduce when using the mdbook binary or installing it via --locked option (which uses v3.0.2).
Similarly to the original reporter I have markdown files which contain english/russian text, containing letter ё (which was suspected to cause the issues in the original report).

❯ mdbook serve
[INFO] (mdbook::book): Book building has started
[INFO] (mdbook::book): Running the html backend

thread 'main' panicked at /Users/xxxxx/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/elasticlunr-rs-3.0.3/src/lang/en.rs:518:47:
index out of bounds: the len is 3 but the index is 18446744073709551615
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: <elasticlunr::lang::en::Stemmer as elasticlunr::pipeline::PipelineFn>::filter
   4: elasticlunr::pipeline::Pipeline::run
   5: elasticlunr::Index::add_doc
   6: mdbook::renderer::html_handlebars::search::add_doc
   7: mdbook::renderer::html_handlebars::search::create_files
   8: <mdbook::renderer::html_handlebars::hbs_renderer::HtmlHandlebars as mdbook::renderer::Renderer>::render
   9: mdbook::book::MDBook::execute_build_process
  10: mdbook::book::MDBook::build
  11: mdbook::cmd::serve::execute
  12: mdbook::main
