### ISSUE TITLE
Need to port the ElasticLunr stemmer

### ISSUE THREAD

**Issue by mattico** [mattico/elasticlunr-rs#4]
Looks like they're off-by-one before the square root, i.e. `sqrt(3)` instead of `sqrt(2)`, etc. Probably something in `Index::add_doc`.

**Comment by mattico** [comment]
After comparing the token counts, I think the discrepancy is due to our stemmer working slightly differently. e.g. "communiti" vs "commun". Since the search algorithm runs the same stemmer to search the trie, ours needs to be identical in order for search to work.

**Comment by cetra3** [comment]
There is the following package that uses the snowball method: https://github.com/CurrySoftware/rust-stemmers

**Comment by cetra3** [comment]
Which you're already using.  Don't mind me!

**Comment by mattico** [comment]
Yep :) That crate passes the stemmer tests from elasticlunr, but it doesn't match for all input I've tried. I've just tried porter_stemmer, and that doesn't even pass the tests.

**Comment by mattico** [comment]
Ok, master now uses a port of the elasticlunr stemmer. There's one issue with it which is that it only removes "ed" from words that end in "ted", etc.

**Comment by mattico** [comment]
Done in  d719f35
